### ISSUE TITLE
Timing issue ?

### ISSUE THREAD

**Issue by jeanmatthieud** [mongoose-os-libs/neopixel#1]
I'm using a WS2812b chip, with the GRB order, and an ESP8266.

On an Ardunio platform, with the [Adafruit Library](https://github.com/adafruit/Adafruit_NeoPixel), everything works fine.

On the same device, with the MOS platform, it's impossible to have a real RED color. A yellow color is displayed instead.

I tried with the JS and C examples.

**Comment by jeanmatthieud** [comment]
In fact, the green is always on, even with:
strip.clear();
strip.setPixel(0, 0, 0, 0);
strip.show();

That's why the red is yellow and the blue is a lighter blue.

Maybe a timing issue as already seen on the FastLed lib:
https://github.com/FastLED/FastLED/issues/104#issuecomment-64829622

**Comment by tripflex** [comment]
@jeanmatthieud are you using SPI on Arduino or bitbanging it like this lib does?  Looks like this lib doesn't support SPI and does the standard bit banging (which is common for WS2812)

**Comment by mamuesp** [comment]
In fact, the timing was a little out of turn. I have fixed this problem and will soon publish a PR with possibilities to configure the timing via `mos.yml`. I mentioned the problem [here](https://gitter.im/cesanta/mongoose-os?at=5c2b87882fd0315409011936). BTW I'm also working on a driver for the APA102 LED.
@tripflex - SPI doesn't work with neopixels because they need a combination of PCM and PWM because they work clockless. They are only controlled by one wire and use different pulse widths to detect `0`and `1`. So a clock cycle within the given time (1.25us) is one bit, and starts with HIGH and drops to LOW, but with different durations. If it is shorter than half the cycles duration, it is considered HIGH and LOW if the drop occurs after half of the cycle duration. A LOW of more than 40 cycles is considered a "reset". This is all these devices may understand ...
In contrast, the APA102, for example, can be controlled via SPI, but here one more connection is required (CLCK), and the data is transmitted with constant pulse width as pulse code. 
Therefore it is clear: for the Neopixel LEDs only bitbanging is possible, or SPI with some external hardware. SPI cannot be "bent" to produce a signal understandable for WS2812/Neopixel.
P.S.: A good explanation might be found [here (Adafruit Neopixel Überguide)](https://learn.adafruit.com/adafruit-neopixel-uberguide/advanced-coding#faq-12)

**Comment by fjp** [comment]
My problem is similar. In my case red seems always on even when using

```
strip.clear();
strip.setPixel(0, 0, 0, 0);
strip.show();
```
@mamuesp were you able to solve this issue?

@rojer could you please take the time to merge the pull requests?

**Comment by mamuesp** [comment]
@fjp - Yes, with the configurable timing settings I figured out the correct timing. The default didn't fit on every occasion. As I have ENOTIME, you may look at my fork: https://github.com/mamuesp/neopixel
Anyway I'm planning to contorl the WS2812 over the RMT module, because for my purpose bitbanging is absolutely no option. That's why I use APA102 over SPI for the moment. Works like a charm.

**Comment by fjp** [comment]
@mamuesp thanks for the reply. I replaced this neopixel lib with yours in my mos.yml followed by `mos build` and `mos flash` but nothing changed, red is still always on :( I am using the WS2812B on the D1 mini rgb shield. 

Do I have to change something else to get the correct timing?

**Comment by fjp** [comment]
@mamuesp I tried with the [example-neopixel-c](https://github.com/mongoose-os-apps/example-neopixel-c), replaced the neopixel lib with yours and it works 👍

In my other [app](https://github.com/fjp/rgb-light-server/blob/master/src/main.c) I am using the http-server lib. In the app's main function I switch the led off but the red channel stays on... Don't know why though.

**Comment by fjp** [comment]
Ok there is something "wrong" with the [http-server lib](https://github.com/mongoose-os-libs/http-server). Everytime I include it in the mos.yml the led keeps switching to red even when I do not include headers or use any of its functions. Is the http-server lib writing to pin 4?

The colors are correct when I don't use the http-server lib:

```
# List of libraries used by this app, in order of initialisation
libs:
    - origin: https://github.com/mongoose-os-libs/boards
    - origin: https://github.com/mamuesp/neopixel
    - origin: https://github.com/mongoose-os-libs/rpc-service-config
    - origin: https://github.com/mongoose-os-libs/rpc-service-fs
    - origin: https://github.com/mongoose-os-libs/rpc-uart
    #- origin: https://github.com/mongoose-os-libs/http-server
```
Any ideas why this is happening?

**Comment by mamuesp** [comment]
@fjp - As bitbanging is blocking everything and time consuming (so e.g. the interrupt handling will be stopped for a moment), there might be side effects so the data transmission won't work accurately. In my opinion this solution will only work as (almost) a standalone function with no other timers, events or interrupts interfering with the process. That's why I switched to APA102, there the data transfer might be handled via SPI in the background.

**Comment by igivc** [comment]
I fixed the issue for WS2812b which I noticed on ESP8266.
Please find the fixed version at 
[https://github.com/galilov/neopixel](https://github.com/galilov/neopixel)
It works well without any issues.

Usage:

```
libs:
  - origin: https://github.com/mongoose-os-libs/boards
  - origin: https://github.com/mongoose-os-libs/ca-bundle
# other libs
  - origin: https://github.com/galilov/neopixel  # link to github
    version: 2.15.ag  # used version
```
It is a very simple fix:

```
void mgos_neopixel_show(struct mgos_neopixel *np) {
  mgos_gpio_write(np->pin, 0);
  mgos_usleep(100);
#if MGOS_ENABLE_BITBANG
  mgos_bitbang_write_bits(np->pin, MGOS_DELAY_100NSEC, 3, 8, 8, 3, np->data,
                          np->num_pixels * NUM_CHANNELS);
#endif
  mgos_gpio_write(np->pin, 0);
  mgos_usleep(100);
  mgos_gpio_write(np->pin, 1);
}
```

I changed timing according to 
[ws2812b doc](https://www.digikey.com/en/datasheets/parallaxinc/parallax-inc-28085-ws2812b-rgb-led-datasheet) which was not really necessary and changed the initial usleep from 60 to 100 uS which fixed the issues for 100%. And the trailing pause was also prolonged from 60 to 100 uS.
